services:
  pg:
    image: postgres:16
    container_name: pg
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: chelsea
      POSTGRES_PASSWORD: chelsea
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"   # 仅绑定本机

  redis:
    image: redis:7
    container_name: redis
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redisdata:/data
    ports:
      - "127.0.0.1:6379:6379"   # 仅绑定本机

  mongo:
    image: mongo:7
    container_name: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "127.0.0.1:27017:27017" # 仅绑定本机
 
  

volumes:
  pgdata:
  redisdata:
  mongodata:

